### ISSUE TITLE
Running with v2.2.0 getting unhandled exception on scan

### ISSUE THREAD

**Issue by derwin12** [stojy/ClrVpin#27]
I put all the directories in .. click the scanner for most recent..
got the following dump.

![2022-04-08 16_12_32-daryl e - TeamViewer - Free license (non-commercial use only)](https://user-images.githubusercontent.com/4643499/162521501-66407992-8c9d-497d-b01b-deacdaefd2ef.png)

**Comment by derwin12** [comment]
---------- System Info ----------
Start Time:            4/8/2022 4:39:13 PM
App:                   ClrVpin
Version:               2.2.0.0
Path:                  C:\Program Files\ClrVpin\ClrVpin.exe
Command Line:          "C:\Program Files\ClrVpin\ClrVpin.dll"
Processor Type:        AMD64 Family 21 Model 1 Stepping 2, AuthenticAMD
Processor Count:       4
Free Physical Memory:  2.7 GB
Free Virtual Memory:   8.8 TB
OS:                    Microsoft Windows NT 6.1.7601 Service Pack 1
64 bit:                True
CLI Version:           6.0.0
---------------------------------  
App started, settings={"PinballFolder":"C:\\Visual Pinball","PinballTablesFolder":"C:\\vp\\tables\\vpx","FrontendFolder":"C:\\PinballX","AllContentTypes":[{"Enum":16,"Category":2,"Extensions":"*.vpx, *.vpt","KindredExtensions":"*.vbs, *.txt, *.pdf","Tip":"Playfield table","ExtensionsList":["*.vpx","*.vpt"],"KindredExtensionsList":["*.vbs","*.txt","*.pdf"],"Folder":"C:\\Visual Pinball\\Tables","Description":"Tables"},{"Enum":17,"Category":2,"Extensions":"*.directb2s","KindredExtensions":"","Tip":"Image used for the backglass","ExtensionsList":["*.directb2s"],"KindredExtensionsList":[""],"Folder":"C:\\Visual Pinball\\Tables","Description":"Backglasses"},{"Enum":18,"Category":2,"Extensions":"*.pov","KindredExtensions":"","Tip":"3D camera configuration","ExtensionsList":["*.pov"],"KindredExtensionsList":[""],"Folder":"C:\\Visual Pinball\\Tables","Description":"Point Of Views"},{"Enum":0,"Category":0,"Extensions":"*.xml","KindredExtensions":"","Tip":"Pinball X or Pinball Y database file","ExtensionsList":["*.xml"],"KindredExtensionsList":[""],"Folder":"C:\\PinballX\\Databases","Description":"Database"},{"Enum":1,"Category":1,"Extensions":"*.mp3, *.wav","KindredExtensions":"","Tip":"Audio used when displaying a table","ExtensionsList":["*.mp3","*.wav"],"KindredExtensionsList":[""],"Folder":"C:\\PinballX\\Media\\Visual Pinball\\Table Audio","Description":"Table Audio"},{"Enum":2,"Category":1,"Extensions":"*.mp3, *.wav","KindredExtensions":"","Tip":"Audio used when launching a table","ExtensionsList":["*.mp3","*.wav"],"KindredExtensionsList":[""],"Folder":"C:\\PinballX\\Media\\Visual Pinball\\Launch Audio","Description":"Launch Audio"},{"Enum":3,"Category":1,"Extensions":"*.f4v, *.mp4, *.mkv","KindredExtensions":"","Tip":"Video used when displaying a table","ExtensionsList":["*.f4v","*.mp4","*.mkv"],"KindredExtensionsList":[""],"Folder":"C:\\PinballX\\Media\\Visual Pinball\\Table Videos","Description":"Table Videos"},{"Enum":4,"Category":1,"Extensions":"*.f4v, *.mp4, *.mkv","KindredExtensions":"","Tip":"Video used when displaying a table\u0027s backglass","ExtensionsList":["*.f4v","*.mp4","*.mkv"],"KindredExtensionsList":[""],"Folder":"C:\\PinballX\\Media\\Visual Pinball\\Backglass Videos","Description":"Backglass Videos"},{"Enum":5,"Category":1,"Extensions":"*.png, *.apng, *.jpg","KindredExtensions":"","Tip":"Image used when displaying a table","ExtensionsList":["*.png","*.apng","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\PinballX\\Media\\Visual Pinball\\Wheel Images","Description":"Wheel Images"},{"Enum":6,"Category":1,"Extensions":"*.f4v, *.mp4, *.mkv","KindredExtensions":"","Tip":"Video used when displaying the topper","ExtensionsList":["*.f4v","*.mp4","*.mkv"],"KindredExtensionsList":[""],"Folder":"C:\\PinballX\\Media\\Visual Pinball\\Topper Videos","Description":"Topper Videos"},{"Enum":7,"Category":1,"Extensions":"*.png, *.jpg, *.swf","KindredExtensions":"","Tip":"Image used when displaying instruction cards","ExtensionsList":["*.png","*.jpg","*.swf"],"KindredExtensionsList":[""],"Folder":"C:\\PinballX\\Media\\Instruction Cards","Description":"Instruction Cards"},{"Enum":8,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\PinballX\\Media\\Flyer Images\\Back","Description":"Flyer Images\\Back"},{"Enum":9,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\PinballX\\Media\\Flyer Images\\Front","Description":"Flyer Images\\Front"},{"Enum":10,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\PinballX\\Media\\Flyer Images\\Inside1","Description":"Flyer Images\\Inside1"},{"Enum":11,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\PinballX\\Media\\Flyer Images\\Inside2","Description":"Flyer Images\\Inside2"},{"Enum":12,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\PinballX\\Media\\Flyer Images\\Inside3","Description":"Flyer Images\\Inside3"},{"Enum":13,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\PinballX\\Media\\Flyer Images\\Inside4","Description":"Flyer Images\\Inside4"},{"Enum":14,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\PinballX\\Media\\Flyer Images\\Inside5","Description":"Flyer Images\\Inside5"},{"Enum":15,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\PinballX\\Media\\Flyer Images\\Inside6","Description":"Flyer Images\\Inside6"}],"BackupFolder":"C:\\ProgramData\\ClrVpin\\backup","TrainerWheels":true,"Scanner":{"SelectedCheckContentTypes":[],"SelectedCheckHitTypes":[],"SelectedFixHitTypes":[],"SelectedMultipleMatchOption":2,"MultipleMatchExceedSizeThresholdPercentage":85},"Rebuilder":{"SourceFolder":"C:\\Users\\virtuapin\\Downloads","DestinationContentType":null,"IgnoreIfSmallerPercentage":75,"IgnoreIWords":["nude","adult","tba","original","orginal","b\u0026w"," bw ","2scr","2 screen"],"DeleteIgnoredFiles":false,"SelectedMatchTypes":[0],"SelectedMergeOptions":[],"SelectedIgnoreOptions":[]},"Importer":{"IncludeOriginalTables":false,"UpdatedAtDateBegin":null,"UpdatedAtDateEnd":null},"Version":2}  

Scanner started, settings={"PinballFolder":"C:\\Visual Pinball","PinballTablesFolder":"C:\\vp\\tables\\vpx","FrontendFolder":"C:\\PinballX","AllContentTypes":[{"Enum":16,"Category":2,"Extensions":"*.vpx, *.vpt","KindredExtensions":"*.vbs, *.txt, *.pdf","Tip":"Playfield table","ExtensionsList":["*.vpx","*.vpt"],"KindredExtensionsList":["*.vbs","*.txt","*.pdf"],"Folder":"C:\\Visual Pinball\\Tables","Description":"Tables"},{"Enum":17,"Category":2,"Extensions":"*.directb2s","KindredExtensions":"","Tip":"Image used for the backglass","ExtensionsList":["*.directb2s"],"KindredExtensionsList":[""],"Folder":"C:\\Visual Pinball\\Tables","Description":"Backglasses"},{"Enum":18,"Category":2,"Extensions":"*.pov","KindredExtensions":"","Tip":"3D camera configuration","ExtensionsList":["*.pov"],"KindredExtensionsList":[""],"Folder":"C:\\Visual Pinball\\Tables","Description":"Point Of Views"},{"Enum":0,"Category":0,"Extensions":"*.xml","KindredExtensions":"","Tip":"Pinball X or Pinball Y database file","ExtensionsList":["*.xml"],"KindredExtensionsList":[""],"Folder":"C:\\PinballX\\Databases","Description":"Database"},{"Enum":1,"Category":1,"Extensions":"*.mp3, *.wav","KindredExtensions":"","Tip":"Audio used when displaying a table","ExtensionsList":["*.mp3","*.wav"],"KindredExtensionsList":[""],"Folder":"C:\\PinballX\\Media\\Visual Pinball\\Table Audio","Description":"Table Audio"},{"Enum":2,"Category":1,"Extensions":"*.mp3, *.wav","KindredExtensions":"","Tip":"Audio used when launching a table","ExtensionsList":["*.mp3","*.wav"],"KindredExtensionsList":[""],"Folder":"C:\\PinballX\\Media\\Visual Pinball\\Launch Audio","Description":"Launch Audio"},{"Enum":3,"Category":1,"Extensions":"*.f4v, *.mp4, *.mkv","KindredExtensions":"","Tip":"Video used when displaying a table","ExtensionsList":["*.f4v","*.mp4","*.mkv"],"KindredExtensionsList":[""],"Folder":"C:\\PinballX\\Media\\Visual Pinball\\Table Videos","Description":"Table Videos"},{"Enum":4,"Category":1,"Extensions":"*.f4v, *.mp4, *.mkv","KindredExtensions":"","Tip":"Video used when displaying a table\u0027s backglass","ExtensionsList":["*.f4v","*.mp4","*.mkv"],"KindredExtensionsList":[""],"Folder":"C:\\PinballX\\Media\\Visual Pinball\\Backglass Videos","Description":"Backglass Videos"},{"Enum":5,"Category":1,"Extensions":"*.png, *.apng, *.jpg","KindredExtensions":"","Tip":"Image used when displaying a table","ExtensionsList":["*.png","*.apng","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\PinballX\\Media\\Visual Pinball\\Wheel Images","Description":"Wheel Images"},{"Enum":6,"Category":1,"Extensions":"*.f4v, *.mp4, *.mkv","KindredExtensions":"","Tip":"Video used when displaying the topper","ExtensionsList":["*.f4v","*.mp4","*.mkv"],"KindredExtensionsList":[""],"Folder":"C:\\PinballX\\Media\\Visual Pinball\\Topper Videos","Description":"Topper Videos"},{"Enum":7,"Category":1,"Extensions":"*.png, *.jpg, *.swf","KindredExtensions":"","Tip":"Image used when displaying instruction cards","ExtensionsList":["*.png","*.jpg","*.swf"],"KindredExtensionsList":[""],"Folder":"C:\\PinballX\\Media\\Instruction Cards","Description":"Instruction Cards"},{"Enum":8,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\PinballX\\Media\\Flyer Images\\Back","Description":"Flyer Images\\Back"},{"Enum":9,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\PinballX\\Media\\Flyer Images\\Front","Description":"Flyer Images\\Front"},{"Enum":10,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\PinballX\\Media\\Flyer Images\\Inside1","Description":"Flyer Images\\Inside1"},{"Enum":11,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\PinballX\\Media\\Flyer Images\\Inside2","Description":"Flyer Images\\Inside2"},{"Enum":12,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\PinballX\\Media\\Flyer Images\\Inside3","Description":"Flyer Images\\Inside3"},{"Enum":13,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\PinballX\\Media\\Flyer Images\\Inside4","Description":"Flyer Images\\Inside4"},{"Enum":14,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\PinballX\\Media\\Flyer Images\\Inside5","Description":"Flyer Images\\Inside5"},{"Enum":15,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\PinballX\\Media\\Flyer Images\\Inside6","Description":"Flyer Images\\Inside6"}],"BackupFolder":"C:\\ProgramData\\ClrVpin\\backup","TrainerWheels":true,"Scanner":{"SelectedCheckContentTypes":["Backglasses"],"SelectedCheckHitTypes":[],"SelectedFixHitTypes":[],"SelectedMultipleMatchOption":2,"MultipleMatchExceedSizeThresholdPercentage":50},"Rebuilder":{"SourceFolder":"C:\\Users\\virtuapin\\Downloads","DestinationContentType":null,"IgnoreIfSmallerPercentage":75,"IgnoreIWords":["nude","adult","tba","original","orginal","b\u0026w"," bw ","2scr","2 screen"],"DeleteIgnoredFiles":false,"SelectedMatchTypes":[0],"SelectedMergeOptions":[],"SelectedIgnoreOptions":[]},"Importer":{"IncludeOriginalTables":false,"UpdatedAtDateBegin":null,"UpdatedAtDateEnd":null},"Version":2}  
Unhandled exception detected

Message: Attempted to divide by zero.
Assembly: ClrVpin, Version=2.2.0.0, Culture=neutral, PublicKeyToken=null
Sender: System.Windows.Threading.Dispatcher
Source: Application.Current.DispatcherUnhandledException 
 System.DivideByZeroException: Attempted to divide by zero.
   at System.Decimal.DecCalc.VarDecDiv(DecCalc& d1, DecCalc& d2)
   at System.Decimal.op_Division(Decimal d1, Decimal d2)
   at ClrVpin.Scanner.ScannerStatisticsViewModel.CreateTotalStatistics()
   at ClrVpin.Shared.StatisticsViewModel.CreateStatistics()
   at ClrVpin.Scanner.ScannerStatisticsViewModel.Show(Window parentWindow, Double left, Double top)
   at ClrVpin.Scanner.ScannerViewModel.ShowResults(ICollection`1 gameFiles, ICollection`1 unmatchedFiles, TimeSpan duration)
   at ClrVpin.Scanner.ScannerViewModel.Start()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__127_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by stojy** [comment]
Fixed so that ClrVpin now accommodates no games in the database file(s) OR no scanner checking criteria is selected.  In theory though the latter shouldn't be possible as the 'start' button is disabled for this scenario.

At any rate, with the fix you should now see "n/a" when calculating the percentage of missing content for either of these scenarios.
<img width="278" alt="image" src="https://user-images.githubusercontent.com/11408611/162565522-ffc3ac89-990e-4f90-8d80-1c9ee5d4eb97.png">
