### ISSUE TITLE
Bombs when trying to rename a file - it thinks it should add a : in the filename...bad

### ISSUE THREAD

**Issue by derwin12** [stojy/ClrVpin#28]
2.2.0
It looks like it wants to use Star Trek: The Next Generation. Of course windows wont let you use that : in there since that denotes a drive name.

![2022-04-08 18_04_53-daryl e - TeamViewer - Free license (non-commercial use only)](https://user-images.githubusercontent.com/4643499/162538181-18f09cdb-9e81-4f55-ab70-3c17334012c1.png)

**Comment by stojy** [comment]
Nice find.  I've managed to reproduce this so it should be an easy fix :)

`---------- System Info ----------
Start Time:            9/04/22 5:40:22 PM
App:                   ClrVpin
Version:               2.3.0.0
Path:                  C:\code\ClrVpin\ClrVpin\bin\Debug\net6.0-windows\ClrVpin.exe
Command Line:          C:\code\ClrVpin\ClrVpin\bin\Debug\net6.0-windows\ClrVpin.dll
Processor Type:        Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
Processor Count:       8
Free Physical Memory:  17.9 GB
Free Virtual Memory:   138.5 TB
OS:                    Microsoft Windows NT 10.0.19044.0
64 bit:                True
CLI Version:           6.0.2
---------------------------------  
App started, settings={"PinballFolder":"C:\\vp\\tables\\vpx","PinballTablesFolder":"C:\\vp\\tables\\vpx","FrontendFolder":"C:\\vp\\apps\\PinballX","AllContentTypes":[{"Enum":16,"Category":2,"Extensions":"*.vpx, *.vpt","KindredExtensions":"*.vbs, *.txt, *.pdf","Tip":"Playfield table","ExtensionsList":["*.vpx","*.vpt"],"KindredExtensionsList":["*.vbs","*.txt","*.pdf"],"Folder":"C:\\vp\\tables\\vpx","Description":"Tables"},{"Enum":17,"Category":2,"Extensions":"*.directb2s","KindredExtensions":"","Tip":"Image used for the backglass","ExtensionsList":["*.directb2s"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\tables\\vpx","Description":"Backglasses"},{"Enum":18,"Category":2,"Extensions":"*.pov","KindredExtensions":"","Tip":"3D camera configuration","ExtensionsList":["*.pov"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\tables\\vpx","Description":"Point Of Views"},{"Enum":0,"Category":0,"Extensions":"*.xml","KindredExtensions":"","Tip":"Pinball X or Pinball Y database file","ExtensionsList":["*.xml"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Databases\\Visual Pinball","Description":"Database"},{"Enum":1,"Category":1,"Extensions":"*.mp3, *.wav","KindredExtensions":"","Tip":"Audio used when displaying a table","ExtensionsList":["*.mp3","*.wav"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Visual Pinball\\Table Audio","Description":"Table Audio"},{"Enum":2,"Category":1,"Extensions":"*.mp3, *.wav","KindredExtensions":"","Tip":"Audio used when launching a table","ExtensionsList":["*.mp3","*.wav"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Visual Pinball\\Launch Audio","Description":"Launch Audio"},{"Enum":3,"Category":1,"Extensions":"*.f4v, *.mp4, *.mkv","KindredExtensions":"","Tip":"Video used when displaying a table","ExtensionsList":["*.f4v","*.mp4","*.mkv"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Visual Pinball\\Table Videos","Description":"Table Videos"},{"Enum":4,"Category":1,"Extensions":"*.f4v, *.mp4, *.mkv","KindredExtensions":"","Tip":"Video used when displaying a table\u0027s backglass","ExtensionsList":["*.f4v","*.mp4","*.mkv"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Visual Pinball\\Backglass Videos","Description":"Backglass Videos"},{"Enum":5,"Category":1,"Extensions":"*.png, *.apng, *.jpg","KindredExtensions":"","Tip":"Image used when displaying a table","ExtensionsList":["*.png","*.apng","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Visual Pinball\\Wheel Images","Description":"Wheel Images"},{"Enum":6,"Category":1,"Extensions":"*.f4v, *.mp4, *.mkv","KindredExtensions":"","Tip":"Video used when displaying the topper","ExtensionsList":["*.f4v","*.mp4","*.mkv"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Visual Pinball\\Topper Videos","Description":"Topper Videos"},{"Enum":7,"Category":1,"Extensions":"*.png, *.jpg, *.swf","KindredExtensions":"","Tip":"Image used when displaying instruction cards","ExtensionsList":["*.png","*.jpg","*.swf"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Instruction Cards","Description":"Instruction Cards"},{"Enum":8,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Flyer Images\\Back","Description":"Flyer Images\\Back"},{"Enum":9,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Flyer Images\\Front","Description":"Flyer Images\\Front"},{"Enum":10,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Flyer Images\\Inside1","Description":"Flyer Images\\Inside1"},{"Enum":11,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Flyer Images\\Inside2","Description":"Flyer Images\\Inside2"},{"Enum":12,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Flyer Images\\Inside3","Description":"Flyer Images\\Inside3"},{"Enum":13,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Flyer Images\\Inside4","Description":"Flyer Images\\Inside4"},{"Enum":14,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Flyer Images\\Inside5","Description":"Flyer Images\\Inside5"},{"Enum":15,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Flyer Images\\Inside6","Description":"Flyer Images\\Inside6"}],"BackupFolder":"C:\\ProgramData\\ClrVpin\\backup","TrainerWheels":true,"MatchFuzzyMinimumPercentage":145,"Scanner":{"SelectedCheckContentTypes":["Launch Audio"],"SelectedCheckHitTypes":[0,1,2,3,4,5,6,7],"SelectedFixHitTypes":[0,2],"SelectedMultipleMatchOption":2,"MultipleMatchExceedSizeThresholdPercentage":85},"Rebuilder":{"SourceFolder":"C:\\vp\\_downloaded\\backglasses","DestinationContentType":"Backglasses","IgnoreIfSmallerPercentage":80,"IgnoreIWords":["nude","adult","tba","original","orginal","b\u0026w"," bw ","2scr","2 screen"],"DeleteIgnoredFiles":true,"SelectedMatchTypes":[0,1,2,4,3],"SelectedMergeOptions":[0,1],"SelectedIgnoreOptions":[0,2,1]},"Importer":{"IncludeOriginalTables":false,"UpdatedAtDateBegin":"2022-03-02T00:00:00","UpdatedAtDateEnd":null},"Version":2}  

Scanner started, settings={"PinballFolder":"C:\\vp\\tables\\vpx","PinballTablesFolder":"C:\\vp\\tables\\vpx","FrontendFolder":"C:\\vp\\apps\\PinballX","AllContentTypes":[{"Enum":16,"Category":2,"Extensions":"*.vpx, *.vpt","KindredExtensions":"*.vbs, *.txt, *.pdf","Tip":"Playfield table","ExtensionsList":["*.vpx","*.vpt"],"KindredExtensionsList":["*.vbs","*.txt","*.pdf"],"Folder":"C:\\vp\\tables\\vpx","Description":"Tables"},{"Enum":17,"Category":2,"Extensions":"*.directb2s","KindredExtensions":"","Tip":"Image used for the backglass","ExtensionsList":["*.directb2s"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\tables\\vpx","Description":"Backglasses"},{"Enum":18,"Category":2,"Extensions":"*.pov","KindredExtensions":"","Tip":"3D camera configuration","ExtensionsList":["*.pov"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\tables\\vpx","Description":"Point Of Views"},{"Enum":0,"Category":0,"Extensions":"*.xml","KindredExtensions":"","Tip":"Pinball X or Pinball Y database file","ExtensionsList":["*.xml"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Databases\\Visual Pinball","Description":"Database"},{"Enum":1,"Category":1,"Extensions":"*.mp3, *.wav","KindredExtensions":"","Tip":"Audio used when displaying a table","ExtensionsList":["*.mp3","*.wav"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Visual Pinball\\Table Audio","Description":"Table Audio"},{"Enum":2,"Category":1,"Extensions":"*.mp3, *.wav","KindredExtensions":"","Tip":"Audio used when launching a table","ExtensionsList":["*.mp3","*.wav"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Visual Pinball\\Launch Audio","Description":"Launch Audio"},{"Enum":3,"Category":1,"Extensions":"*.f4v, *.mp4, *.mkv","KindredExtensions":"","Tip":"Video used when displaying a table","ExtensionsList":["*.f4v","*.mp4","*.mkv"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Visual Pinball\\Table Videos","Description":"Table Videos"},{"Enum":4,"Category":1,"Extensions":"*.f4v, *.mp4, *.mkv","KindredExtensions":"","Tip":"Video used when displaying a table\u0027s backglass","ExtensionsList":["*.f4v","*.mp4","*.mkv"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Visual Pinball\\Backglass Videos","Description":"Backglass Videos"},{"Enum":5,"Category":1,"Extensions":"*.png, *.apng, *.jpg","KindredExtensions":"","Tip":"Image used when displaying a table","ExtensionsList":["*.png","*.apng","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Visual Pinball\\Wheel Images","Description":"Wheel Images"},{"Enum":6,"Category":1,"Extensions":"*.f4v, *.mp4, *.mkv","KindredExtensions":"","Tip":"Video used when displaying the topper","ExtensionsList":["*.f4v","*.mp4","*.mkv"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Visual Pinball\\Topper Videos","Description":"Topper Videos"},{"Enum":7,"Category":1,"Extensions":"*.png, *.jpg, *.swf","KindredExtensions":"","Tip":"Image used when displaying instruction cards","ExtensionsList":["*.png","*.jpg","*.swf"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Instruction Cards","Description":"Instruction Cards"},{"Enum":8,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Flyer Images\\Back","Description":"Flyer Images\\Back"},{"Enum":9,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Flyer Images\\Front","Description":"Flyer Images\\Front"},{"Enum":10,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Flyer Images\\Inside1","Description":"Flyer Images\\Inside1"},{"Enum":11,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Flyer Images\\Inside2","Description":"Flyer Images\\Inside2"},{"Enum":12,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Flyer Images\\Inside3","Description":"Flyer Images\\Inside3"},{"Enum":13,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Flyer Images\\Inside4","Description":"Flyer Images\\Inside4"},{"Enum":14,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Flyer Images\\Inside5","Description":"Flyer Images\\Inside5"},{"Enum":15,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Flyer Images\\Inside6","Description":"Flyer Images\\Inside6"}],"BackupFolder":"C:\\ProgramData\\ClrVpin\\backup","TrainerWheels":true,"MatchFuzzyMinimumPercentage":145,"Scanner":{"SelectedCheckContentTypes":["Launch Audio"],"SelectedCheckHitTypes":[0,1,2,3,4,5,6,7],"SelectedFixHitTypes":[0,2],"SelectedMultipleMatchOption":2,"MultipleMatchExceedSizeThresholdPercentage":85},"Rebuilder":{"SourceFolder":"C:\\vp\\_downloaded\\backglasses","DestinationContentType":"Backglasses","IgnoreIfSmallerPercentage":80,"IgnoreIWords":["nude","adult","tba","original","orginal","b\u0026w"," bw ","2scr","2 screen"],"DeleteIgnoredFiles":true,"SelectedMatchTypes":[0,1,2,4,3],"SelectedMergeOptions":[0,1],"SelectedIgnoreOptions":[0,2,1]},"Importer":{"IncludeOriginalTables":false,"UpdatedAtDateBegin":"2022-03-02T00:00:00","UpdatedAtDateEnd":null},"Version":2}  
Fixing.. table: Star Trek - The Next Generation (Williams 1993), description: Star Trek: The Next Generation (Williams 1993), type: Table Name, content: Launch Audio, multi option: Prefer Most Recent and Exceeds Size Threshold (criteria: 85.00%)  
- matched (score: n/a)..
  source: 96.6 KB  27/03/21 17:18:21 - C:\vp\apps\PinballX\Media\Visual Pinball\Launch Audio\Star Trek - The Next Generation (Williams 1993).mp3  
- renaming (skipped: trainer wheels)..
  source: 96.6 KB  27/03/21 17:18:21 - C:\vp\apps\PinballX\Media\Visual Pinball\Launch Audio\Star Trek - The Next Generation (Williams 1993).mp3
  dest:   (n/a: new file)            - C:\vp\apps\PinballX\Media\Visual Pinball\Launch Audio\Star Trek: The Next Generation (Williams 1993).mp3  

Scanner started, settings={"PinballFolder":"C:\\vp\\tables\\vpx","PinballTablesFolder":"C:\\vp\\tables\\vpx","FrontendFolder":"C:\\vp\\apps\\PinballX","AllContentTypes":[{"Enum":16,"Category":2,"Extensions":"*.vpx, *.vpt","KindredExtensions":"*.vbs, *.txt, *.pdf","Tip":"Playfield table","ExtensionsList":["*.vpx","*.vpt"],"KindredExtensionsList":["*.vbs","*.txt","*.pdf"],"Folder":"C:\\vp\\tables\\vpx","Description":"Tables"},{"Enum":17,"Category":2,"Extensions":"*.directb2s","KindredExtensions":"","Tip":"Image used for the backglass","ExtensionsList":["*.directb2s"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\tables\\vpx","Description":"Backglasses"},{"Enum":18,"Category":2,"Extensions":"*.pov","KindredExtensions":"","Tip":"3D camera configuration","ExtensionsList":["*.pov"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\tables\\vpx","Description":"Point Of Views"},{"Enum":0,"Category":0,"Extensions":"*.xml","KindredExtensions":"","Tip":"Pinball X or Pinball Y database file","ExtensionsList":["*.xml"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Databases\\Visual Pinball","Description":"Database"},{"Enum":1,"Category":1,"Extensions":"*.mp3, *.wav","KindredExtensions":"","Tip":"Audio used when displaying a table","ExtensionsList":["*.mp3","*.wav"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Visual Pinball\\Table Audio","Description":"Table Audio"},{"Enum":2,"Category":1,"Extensions":"*.mp3, *.wav","KindredExtensions":"","Tip":"Audio used when launching a table","ExtensionsList":["*.mp3","*.wav"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Visual Pinball\\Launch Audio","Description":"Launch Audio"},{"Enum":3,"Category":1,"Extensions":"*.f4v, *.mp4, *.mkv","KindredExtensions":"","Tip":"Video used when displaying a table","ExtensionsList":["*.f4v","*.mp4","*.mkv"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Visual Pinball\\Table Videos","Description":"Table Videos"},{"Enum":4,"Category":1,"Extensions":"*.f4v, *.mp4, *.mkv","KindredExtensions":"","Tip":"Video used when displaying a table\u0027s backglass","ExtensionsList":["*.f4v","*.mp4","*.mkv"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Visual Pinball\\Backglass Videos","Description":"Backglass Videos"},{"Enum":5,"Category":1,"Extensions":"*.png, *.apng, *.jpg","KindredExtensions":"","Tip":"Image used when displaying a table","ExtensionsList":["*.png","*.apng","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Visual Pinball\\Wheel Images","Description":"Wheel Images"},{"Enum":6,"Category":1,"Extensions":"*.f4v, *.mp4, *.mkv","KindredExtensions":"","Tip":"Video used when displaying the topper","ExtensionsList":["*.f4v","*.mp4","*.mkv"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Visual Pinball\\Topper Videos","Description":"Topper Videos"},{"Enum":7,"Category":1,"Extensions":"*.png, *.jpg, *.swf","KindredExtensions":"","Tip":"Image used when displaying instruction cards","ExtensionsList":["*.png","*.jpg","*.swf"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Instruction Cards","Description":"Instruction Cards"},{"Enum":8,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Flyer Images\\Back","Description":"Flyer Images\\Back"},{"Enum":9,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Flyer Images\\Front","Description":"Flyer Images\\Front"},{"Enum":10,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Flyer Images\\Inside1","Description":"Flyer Images\\Inside1"},{"Enum":11,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Flyer Images\\Inside2","Description":"Flyer Images\\Inside2"},{"Enum":12,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Flyer Images\\Inside3","Description":"Flyer Images\\Inside3"},{"Enum":13,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Flyer Images\\Inside4","Description":"Flyer Images\\Inside4"},{"Enum":14,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Flyer Images\\Inside5","Description":"Flyer Images\\Inside5"},{"Enum":15,"Category":1,"Extensions":"*.png, *.jpg","KindredExtensions":"","Tip":"Image used when displaying flyer","ExtensionsList":["*.png","*.jpg"],"KindredExtensionsList":[""],"Folder":"C:\\vp\\apps\\PinballX\\Media\\Flyer Images\\Inside6","Description":"Flyer Images\\Inside6"}],"BackupFolder":"C:\\ProgramData\\ClrVpin\\backup","TrainerWheels":false,"MatchFuzzyMinimumPercentage":145,"Scanner":{"SelectedCheckContentTypes":["Launch Audio"],"SelectedCheckHitTypes":[0,1,2,3,4,5,6,7],"SelectedFixHitTypes":[0,2],"SelectedMultipleMatchOption":2,"MultipleMatchExceedSizeThresholdPercentage":85},"Rebuilder":{"SourceFolder":"C:\\vp\\_downloaded\\backglasses","DestinationContentType":"Backglasses","IgnoreIfSmallerPercentage":80,"IgnoreIWords":["nude","adult","tba","original","orginal","b\u0026w"," bw ","2scr","2 screen"],"DeleteIgnoredFiles":true,"SelectedMatchTypes":[0,1,2,4,3],"SelectedMergeOptions":[0,1],"SelectedIgnoreOptions":[0,2,1]},"Importer":{"IncludeOriginalTables":false,"UpdatedAtDateBegin":"2022-03-02T00:00:00","UpdatedAtDateEnd":null},"Version":2}  
Fixing.. table: Star Trek - The Next Generation (Williams 1993), description: Star Trek: The Next Generation (Williams 1993), type: Table Name, content: Launch Audio, multi option: Prefer Most Recent and Exceeds Size Threshold (criteria: 85.00%)  
- matched (score: n/a)..
  source: 96.6 KB  27/03/21 17:18:21 - C:\vp\apps\PinballX\Media\Visual Pinball\Launch Audio\Star Trek - The Next Generation (Williams 1993).mp3  
- renaming..
  source: 96.6 KB  27/03/21 17:18:21 - C:\vp\apps\PinballX\Media\Visual Pinball\Launch Audio\Star Trek - The Next Generation (Williams 1993).mp3
  dest:   (n/a: new file)            - C:\vp\apps\PinballX\Media\Visual Pinball\Launch Audio\Star Trek: The Next Generation (Williams 1993).mp3  
Unhandled exception detected

Message: The parameter is incorrect.
Assembly: ClrVpin, Version=2.3.0.0, Culture=neutral, PublicKeyToken=null
Sender: System.Windows.Threading.Dispatcher
Source: Application.Current.DispatcherUnhandledException 
 System.IO.IOException: The parameter is incorrect.
   at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)
   at ClrVpin.Shared.FileUtils.Rename(String sourceFile, String destinationFile) in C:\code\ClrVpin\ClrVpin\Shared\FileUtils.cs:line 243
   at ClrVpin.Shared.FileUtils.Rename(String sourceFile, String newFile, HitTypeEnum hitTypeEnum, String contentType, Action`1 backupAction) in C:\code\ClrVpin\ClrVpin\Shared\FileUtils.cs:line 129
   at ClrVpin.Shared.FileUtils.Rename(Hit hit, Game game, ICollection`1 supportedHitTypes, IEnumerable`1 kindredExtensions) in C:\code\ClrVpin\ClrVpin\Shared\FileUtils.cs:line 72
   at ClrVpin.Scanner.ScannerUtils.FixOrderedHits(ICollection`1 orderedHits, List`1 gameFiles, Game game) in C:\code\ClrVpin\ClrVpin\Scanner\ScannerUtils.cs:line 205
   at ClrVpin.Scanner.ScannerUtils.<>c__DisplayClass4_3.<Fix>b__7(Game game) in C:\code\ClrVpin\ClrVpin\Scanner\ScannerUtils.cs:line 140
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at ClrVpin.Scanner.ScannerUtils.<>c__DisplayClass4_0.<Fix>b__2(ContentType contentType) in C:\code\ClrVpin\ClrVpin\Scanner\ScannerUtils.cs:line 108
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at ClrVpin.Scanner.ScannerUtils.Fix(ICollection`1 games, String backupFolder, Action`2 updateProgress) in C:\code\ClrVpin\ClrVpin\Scanner\ScannerUtils.cs:line 97
   at ClrVpin.Scanner.ScannerUtils.<>c__DisplayClass3_0.<FixAsync>b__0() in C:\code\ClrVpin\ClrVpin\Scanner\ScannerUtils.cs:line 71
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at ClrVpin.Scanner.ScannerUtils.FixAsync(List`1 games, String backupFolder, Action`2 updateProgress) in C:\code\ClrVpin\ClrVpin\Scanner\ScannerUtils.cs:line 71
   at ClrVpin.Scanner.ScannerViewModel.Start() in C:\code\ClrVpin\ClrVpin\Scanner\ScannerViewModel.cs:line 205
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

**Comment by stojy** [comment]
Apparently the colon is an invalid character not supported by Windows.  I'll make some changes to ensure file operations with colons (and some other special characters) are no longer attempted by ClrVpin.

Arguably though, I'd consider this a bug in PinballX/Y as they shouldn't allow invalid identifiers in the database file that can't be mapped to file names.  You could raise a bug on those apps (difficult for PInballX as it's not open source), but in the meantime if you want that audio file to play in PinballX/Y then you'll need to rename the description in your xml file.

FYI, the next major feat for ClrVpin is to write to the xml file.  It's intended mostly for missing content, but I'll also add in a 'fix invalid character' option to cater for this.  But this is a few months away I suspect.

**Comment by stojy** [comment]
Invalid database (xml) file entries that requires the file to be renamed with invalid characters will now be skipped instead of crashing the app.

<img width="1313" alt="image" src="https://user-images.githubusercontent.com/11408611/162578575-771f6fd7-5e82-44e7-a02e-5cc2ed9a0682.png">

**Comment by derwin12** [comment]
Its been a couple years since I updated my cabinet .. i wasnt sure where it
was getting this description. I assumed it was from your online db. I guess
u are saying it is from my pinballx db. If so easy change on my part.
Thanks for the work.
I will see if I can get your latest version to work on my machine again..
