### ISSUE TITLE
Unhandled Error - The 'manufacturer' start tag on line 5 position 26 does not match the end tag of 'game'. Line 13, position 4.

### ISSUE THREAD

**Issue by MikedaSpike** [stojy/ClrVpin#47]
**Describe the bug**
During launch of the application it crashes when Fuzzy search is checked
My assumption is that it cannot handle my XML file type

**To Reproduce**

**Expected behavior**
Program should start correctly ? Handle the XML file correctly 

**Screenshots**
![image](https://user-images.githubusercontent.com/48748234/182759975-a65b25f8-7422-42fe-a7fe-2f7c412c5253.png)

**Additional context**
see ClrVpin.log
[ClrVpin.log](https://github.com/stojy/ClrVpin/files/9256546/ClrVpin.log)

**Comment by stojy** [comment]
hi @MikedaSpike, thanks for submitting the bug report.

I reckon you're right, it sounds like the .net xml parser doesn't think your xml file is well formatted.  At a guess, you might be missing a closing tag for <manufactuer> or perhaps your manufacturer description includes a name with a tag in it.

If you can upload the first 50ish lines of your xml file I should be able to confirm.  Alternatively, feel free to upload the whole xml file and I'll make sure the rest of it is ok too.

Depending on the issue, I might be able to cleanse the xml file before it gets parsed.

**Comment by stojy** [comment]
Another option is upload your xml file into an online xml file parser to confirm it looks ok.  For example.. https://codebeautify.org/xmlvalidator

**Comment by stojy** [comment]
Added a user friendly dialog for invalid xml files.. instead of the 'catch all' unhandled error dialog which submits a bug to github.

It's still quite technical though, but hopefully won't be seen too often :)

<img width="1151" alt="image" src="https://user-images.githubusercontent.com/11408611/183017524-d1a34960-0ac9-4703-b2f9-56f66331f3a5.png">

**Comment by MikedaSpike** [comment]
When I'm at the cab, i will do the steps. 
Xml is fine as it is working with PBX.
It is a slighty modified one, as ot is created with DBM. 
On top of my head , an empty entry will only have <entry/> (where entry is the name field) instead of the closing  tag.

**Comment by stojy** [comment]
Sounds good.  I'll be very keen to know why the xml file doesn't parse.. especially since it works with PBX.

**Comment by MikedaSpike** [comment]
> Another option is upload your xml file into an online xml file parser to confirm it looks ok. For example.. https://codebeautify.org/xmlvalidator

Xml file is valid, according to the site.

Here are the first 3 table entries

<?xml version="1.0" encoding="Windows-1252"?>
<menu>
    <game name="_123(Talleres de Llobregat 1973)">
        <description>1-2-3 (Talleres de Llobregat 1973)</description>
        <rom>TlD_123</rom>
        <manufacturer>Talleres de Llobregat</manufacturer>
        <year>1973</year>
        <type>EM</type>
        <hidedmd>True</hidedmd>
        <hidetopper>True</hidetopper>
        <hidebackglass>False</hidebackglass>
        <enabled>True</enabled>
        <rating>0</rating>
        <players>1</players>
        <comment />
        <theme>TV Game Show</theme>
        <author>jpsalas, akiles50000, Loserman76</author>
        <version>1.0.2</version>
        <IPDBnr>5247</IPDBnr>
        <dateadded>1900-01-01 00:00:00</dateadded>
        <datemodified>2022-01-20 06:02:04</datemodified>
    </game>
    <game name="2001 (Gottlieb 1971)">
        <description>2001 (Gottlieb 1971)</description>
        <rom>GTB2001_1971</rom>
        <manufacturer>Gottlieb</manufacturer>
        <year>1971</year>
        <type>EM</type>
        <hidedmd>True</hidedmd>
        <hidetopper>True</hidetopper>
        <hidebackglass>False</hidebackglass>
        <enabled>True</enabled>
        <rating>0</rating>
        <players>1</players>
        <comment />
        <theme>Fantasy</theme>
        <author />
        <version>1.0</version>
        <IPDBnr>2697</IPDBnr>
        <dateadded>2020-04-11 14:58:29</dateadded>
        <datemodified>2017-12-25 23:59:59</datemodified>
    </game>
    <game name="24 (Stern2009)EmperorModv1.1">
        <description>24™ (Stern 2009)</description>
        <rom>twenty4_150</rom>
        <manufacturer>Stern</manufacturer>
        <year>2009</year>
        <type>SS</type>
        <hidedmd>True</hidedmd>
        <hidetopper>True</hidetopper>
        <hidebackglass>False</hidebackglass>
        <enabled>True</enabled>
        <rating>0</rating>
        <players>4</players>
        <comment />
        <theme>Licensed Theme - Television Show - Law</theme>
        <author>Freneticamnesic</author>
        <version>2.0.1</version>
        <IPDBnr>5419</IPDBnr>
        <dateadded>1900-01-01 00:00:00</dateadded>
        <datemodified>2021-09-26 06:20:30</datemodified>
    </game>

**Comment by stojy** [comment]
You're right, that XML snippet does look perfectly valid.  I terminated it with a closing </menu> tag and it parsed fine..
![image](https://user-images.githubusercontent.com/11408611/183224193-da32d0bb-4029-420b-8dfd-ebe614000357.png)


Based on your initial bug report, I suspect it's a _different_ file (in the same folder) that can't be parsed.  The crash you reported has the 'manufacturer' tag on line 5, where as the example above has it on line 6.

Note, ClrVpin will load all of the *.xml database files that exist within the folder.

**Comment by MikedaSpike** [comment]
You are right, Must be another file, If I remove all other files from that directory and only leave the "visual pinball.xml", it is starting fine.
Maybe a file handling that will show which file is causing it, as the log doesn't show what file is causing this (I have multiple XML files in my visual pinball database directory)
But now it starts fine

**Comment by stojy** [comment]
Agreed.  The new dialog (shown above) does exactly that.. specifies which file can't be parsed.

I'll release a new version with the dialog shortly.

**Comment by stojy** [comment]
This version should provide what you need to identify the problem file.. https://github.com/stojy/ClrVpin/releases/tag/4.0.1

**Comment by stojy** [comment]
Hopefully you've identified the file and problem.  I'll close out this issue, but if you believe it's a bug then i can re-open it.

**Comment by MikedaSpike** [comment]
You can close it. It is now showing the incorrect file. Thanks
