### ISSUE TITLE
Unhandled Error - <add summary description here>

### ISSUE THREAD

**Issue by strangeleo7** [stojy/ClrVpin#49]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by stojy** [comment]
hi @strangeleo7, sorry to hear you had a crash.  If you've got some details then I'd be happy to investigate and/or fix it.
